name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: yarn --pure-lockfile
      - name: linter
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          eslint_flags: ./src ./test ./types --ext .ts --ext .tsx
          reporter: github-check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: yarn --pure-lockfile
        name: Install dependencies
      - run: yarn test --coverage
        name: Run tests
        env:
          CI: true
